on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Org Authentication' 
         run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --setdefaultdevhubusername
    
