on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  uses: sfdx-actions/setup-sfdx@v1
        
      -  name: 'Salesforce Org Authentication' 
         run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=${{ secrets.SALESFORCE_SERVER_KEY }} --setdefaultdevhubusername
    
