name: Salesforce Merge Pull Request

on:
  push:
    branches:
      - develop
      - r1-release
      - main

jobs:
  merge_pull_request:
    name: MERGE PULL REQUEST
    runs-on: ubuntu-latest
    timeout-minutes: 180

    container:
      image: salesforce/cli:2.92.5-full

    env:
      ORG_NAME: NCSIT-DevOpsOrg
      REPO_NAME: Phoenix-SalesCloud
      # Add additional Salesforce variables if needed, using secrets for sensitive info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
