name: Salesforce Merge Pull Request

on:
  push:
    branches:
      - develop
      - r1-release
      - main

jobs:
  merge_pull_request:
    name: MERGE PULL REQUEST
    runs-on: ubuntu-latest
    timeout-minutes: 180

    container:
      image: salesforce/cli:2.92.5-full

    env:
      ORG_NAME: NCSIT-DevOpsOrg
      REPO_NAME: Phoenix-SalesCloud
      # Add additional Salesforce variables if needed, using secrets for sensitive info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run sfdx git delta and create delta
        run: |
          export HOME="/root"
          mkdir force-app-delta
          sf sgd source delta --to HEAD --from HEAD^ -s force-app --generate-delta --output ./force-app-delta/
      
      - name: Display Package to Deploy
        run: cat force-app-delta/package/package.xml
      
      - name: Display Package to Destroy
        run: cat force-app-delta/destructiveChanges/destructiveChanges.xml
