on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Org Authentication' 
         run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername
      
      -  name: 'Convert Metadata'
         run: sfdx force:source:convert --rootdir=force-app --outputdir=convert

      -  name: 'Run Validation on Metadata'
         run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30
